# netlify.toml
[build]
  publish = ".next"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin"
    Access-Control-Max-Age = "86400"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"